npm i discord.js
npm i ms
npm i ms
npm i node-superfetch
npm i guildMemberAd
npm i guildMemberAdd
npm i moment-duration-format
npm i ffmpeg
npm i ytdl-core
npm i serverQueue
npm i ffmpeg
npm i opusscript
npm i google-tts-api
npm i fs
npm i bg
npm i userimg
npm i discord.js
refresh
npm i fs
npm i fs.readdir
npm i fs.readdir
npm i err
npm i fs.js
npm i weather.js
npm i weather-js
npm i discord.js
npm i google-tts-api
npm i node-opus
npm i ms
npm i args
npm i command
npm i snekfetch
npm i canvas
